---
- name: Playbook to manage Haisi's Dev Setup
  hosts: localhost
  connection: local

  vars_files:
    - vars.yml

  tasks:
    - name: load custom vars
      include_vars: ../vars.yml
      tags:
        - always

    - include: tasks/link_files.yml
      tags:
        - links

    - include: tasks/packages.yml
      tags:
        - packages

    - include: tasks/shells.yml
      tags:
        - shells

    - include: tasks/macos_defaults.yml
      when: ansible_os_family == "Darwin"
      tags:
        - macos_defaults

    - include: tasks/gnome_defaults.yml
      when: ansible_os_family == "Debian"
      tags:
        - gnome_defaults
    
  handlers:
  - name: Kill Dock
    command: killall Dock

  - name: Kill Finder
    command: killall Finder

  - name: Kill Safari
    command: killall Safari
    ignore_errors: yes

  - name: Kill Terminal
    command: killall Terminal
    ignore_errors: yes


  roles:
#    - role: geerlingguy.mac.homebrew
#      tags: ["dock"]
    - role: geerlingguy.mac.dock
      tags: ["dock"]