---
- name: Playbook to manage Haisi's dotfiles (https://github.com/haisi/dotfiles)
  hosts: localhost
  connection: local
  tasks:
    - name: load custom vars
      include_vars: ../vars.yml
      tags:
        - always

    - include: tasks/link_files.yml
      tags:
        - links

    - include: tasks/packages.yml
      tags:
        - packages

    
    - include: tasks/shells.yml
      tags:
        - shells
    
  handlers:
  - name: Kill Dock
    command: killall Dock

  - name: Kill Finder
    command: killall Finder

  - name: Kill Safari
    command: killall Safari
    ignore_errors: yes

  - name: Kill Terminal
    command: killall Terminal
    ignore_errors: yes