---
- name: link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/my-mac/dotfiles/.aliases", dest: "~/.aliases"}
    - { src: "~/my-mac/dotfiles/.exports", dest: "~/.exports"}
    - { src: "~/my-mac/dotfiles/.functions", dest: "~/.functions"}
    - { src: "~/my-mac/dotfiles/.path", dest: "~/.path"}
    - { src: "~/my-mac/dotfiles/.zshrc", dest: "~/.zshrc"}

- name: copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "~/my-mac/dotfiles/spectacle.json", dest: "~/Library/Application\ Support/Spectacle/Shortcuts.json"}