---
- name: link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    # force: yes required because .gitconfig file might already exist causing the link creation to fail
    force: yes
  loop:
    - { src: "~/my-mac/dotfiles/.aliases", dest: "~/.aliases"}
    - { src: "~/my-mac/dotfiles/.exports", dest: "~/.exports"}
    - { src: "~/my-mac/dotfiles/.functions", dest: "~/.functions"}
    - { src: "~/my-mac/dotfiles/.path", dest: "~/.path"}
    - { src: "~/my-mac/dotfiles/.zprofile", dest: "~/.zprofile"}
    - { src: "~/my-mac/dotfiles/.zshrc", dest: "~/.zshrc"}
    - { src: "~/my-mac/dotfiles/.p10k.zsh", dest: "~/.p10k.zsh"}
    - { src: "~/my-mac/dotfiles/.gitconfig", dest: "~/.gitconfig"}
    - { src: "~/my-mac/dotfiles/.gitignore_global", dest: "~/.gitignore_global"}

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "~/Library/Application\ Support/Spectacle"
    state: directory
    mode: '0755'

- name: copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "~/my-mac/dotfiles/spectacle.json", dest: "~/Library/Application\ Support/Spectacle/Shortcuts.json"}

- name: Create empty zsh history file
  copy:
    content: ""
    path: "~/Library/Application\ Support/Spectacle"
    force: false
    state: file
    mode: '0666'